service/config/routes.rb
Rails.application.routes.draw do
  [:channels, :providers, :categories, :programs, :program_episodes, :short_clip_priorities,
      :short_clip_promotions].each do |resource|
    resources resource do
      post 'import', :on => :collection, :defaults => { :format => 'json'}
      get 'dump', :on => :collection, :defaults => { :format => 'json'}
    end
  end

  resources :channel_schedule_versions
    
  [:programs, :schedule_programs, :short_clips, :program_episodes, :schedule_program_episodes, 
      :final_schedules].each do |resource|
    resources resource do
      post 'import', :on => :collection, :defaults => { :format => 'json'}
      get 'dump', :on => :collection, :defaults => { :format => 'json'}
      put :index, :on => :collection
      put 'new', :on => :collection
      put 'edit', :on => :member
    end
  end
    
  [:videos].each do |resource|
    resources resource do
      post 'import', :on => :collection, :defaults => { :format => 'json'}
      get 'dump', :on => :collection, :defaults => { :format => 'json'}
      post 'dump', :on => :collection, :defaults => { :format => 'json'}
      put :index, :on => :collection
      get 'sync', :on => :collection
    end
  end
 
  root :to => "program#index"
 

end

service/app/views/layouts/_schedule.html.erb
<h3><%= name %></h3>
<table id='schedule_list' class="display display_only">
  <thead>
    <tr>
      <th align="left">Time</th>
      <th align="left">Program</th>
      <th align="left">Duration</th>
      <th align="left">Episode</th>
      <th align="left">Video</th>
      <th align="left">Remark</th>
      <% if viewable -%>
        <th align="left">Delete</th>
      <% end -%>
    </tr>
  </thead>

  <tbody>
    <% scheduled.each do |record| %>
      <tr><td>
         <% if record["color"].nil? -%>
            <%= Utility.durationStr(record["time"]) %>
          <% else -%>
            <span style="color: <%= record["color"] %>"><%= Utility.durationStr(record["time"]) %></span>
          <% end -%></td>
        <td><% if viewable -%>
          <%= link_to record["program"], action: 'show', id: record["id"]  %>
        <% else -%>
          <%= record["program"] %>
        <% end -%></td>
        <td><%= Utility.durationStr(record["duration"]) %></td>
        <td><%= record["episode"] %></td>
        <td><% if !record["video_name"].nil? -%>
           <%= link_to record["video_name"], controller: 'videos', action: 'show', id: record["video_id"]  %>
        <% end -%></td>
        <td><%= record["remark"] %></td>
        <% if viewable -%>
          <td><%= link_to 'Delete', {action: 'destroy', id: record["id"]}, method: 'delete', data: { confirm: 'Are you sure?' } %></td>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
</table>

service/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Schedule Service</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag '//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css' %>
  <%= javascript_include_tag '//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js' %>

  <script>
    $(document).ready(function(){
      $('table.display_only').DataTable({
        "ordering": false,
        "bFilter": false,
        "bPaginate": false,
        "bInfo": false
      });
      $('table.data_full').DataTable({
        "pageLength": 100,
        "order": []
      });
      $('.datepicker').datepicker({
        format: 'yyyy-mm-dd'
      });
     })
  </script>
  
  <% if content_for? :for_head %>
    <%= yield :for_head %>
  <% end %>
</head>
<body>
  <div style="background:#FFF0E0">
    <div class="left_menu">
      <ul>
        <% if @family == "schedule" %>
          <li><%=link_to_unless params[:controller] == "schedule_programs", "Scheduled Program", schedule_programs_path, {:class=>"menu"} %></li>
          <li><%=link_to_unless params[:controller] == "schedule_program_episodes", "Scheduled Episode", schedule_program_episodes_path, {:class=>"menu"} %></li>
          <li><%=link_to_unless params[:controller] == "final_schedules", "Final Schedule", final_schedules_path, {:class=>"menu"} %></li>
          <li><%=link_to_unless params[:controller] == "channels", "Channel", channels_path, {:class=>"menu"}%></li>
          <li><%=link_to_unless params[:controller] == "channel_schedule_versions", "Version", channel_schedule_versions_path, {:class=>"menu"} %></li>
          <li><%=link_to_unless params[:controller] == "short_clip_priorities", "Short Clip Priority", short_clip_priorities_path, {:class=>"menu"} %></li>
          <li><%=link_to_unless params[:controller] == "short_clip_promotions", "Short Clip Promotion", short_clip_promotions_path, {:class=>"menu"} %></li>
        <% else %>
          <li><%=link_to_unless params[:controller] == "programs", "Program", programs_path, {:class=>"menu"} %></li>
          <li><%=link_to_unless params[:controller] == "program_episodes", "Episode", program_episodes_path, {:class=>"menu"} %></li>
          <li><%=link_to_unless params[:controller] == "short_clips", "Short Clips", short_clips_path, {:class=>"menu"} %></li>
          <li><%=link_to_unless params[:controller] == "videos", "Video", videos_path, {:class=>"menu"} %></li>
          <li><%=link_to_unless params[:controller] == "providers", "Provider", providers_path, {:class=>"menu"} %></li>
          <li><%=link_to_unless params[:controller] == "categories", "Category", categories_path, {:class=>"menu"} %></li>
        <% end %>
      </ul>
    </div>
    <div class="right_menu">
      <ul>
        <li><%=link_to_unless @family == "program", "PROGRAM", {controller: "programs", action: "index"}, {:class=>"menu"} %></li>
        <li><%=link_to_unless @family == "schedule", "SCHEDULE", {controller: "schedule_programs", action: "index"}, {:class=>"menu"} %></li>
      </ul>
    </div>
    <div style="clear: both;"></div>
  </div>
  <div style="background:#FFFFF0">
    <div class="left_menu">
      <ul>
          <li><%=link_to_unless params[:action] == "index", "List", {action: "index"}, {:class=>"menu"} %></li>
          <% if !["program_episodes", "short_clips"].include?(params[:controller]) %>
            <li><%=link_to_unless params[:action] == "new", "Add", {action: "new"}, {:class=>"menu"} %></li>
          <% end %> 
      </ul>
    </div>
    <div style="clear: both;"></div>
  </div>
  <%= yield %>

</body>
</html>